server:
  servlet:
    context-path: /auth
  port: 9003
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: travel_auth
#  datasource:
#    hikari:
#      maximum-pool-size: 5
#      connection-timeout: 10000
#      max-lifetime: 1000
#      connection-test-query: SELECT 1
#      minimum-idle: 0
#      idle-timeout: 10000
#    url: jdbc:postgresql://localhost:5432/travel
#    username: travel
#    password: travel
#    driver-class-name: org.postgresql.Driver
#service:
#  oauth:
#    token:
#      inMemory: true