spring:
  application:
    name: registry
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9000
      fail-fast: true
      username: clouduser
      password: tv-MpZ6D6@N%J&n?
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
