spring:
  application:
    name: registry
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9000
      fail-fast: true
      username: clouduser
      password: tv-MpZ6D6@N%J&n?
security:
  user:
    name: admin
    password: password
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
